document.getElementById('search-input').addEventListener('input', function() {
    let input = this.value.toLowerCase();
    let resultsList = document.getElementById('results-list');
    resultsList.innerHTML = '';

    let words = [
        "avalanche - лавина",
  "drought wipes out - сушата заличава, ликвидира",
  "earthquake - земетресение",
  "epidemic breaks out - избухва епидемия, епидемичен",
  "flood hits the area - наводнението удари района",
  "hurricane strikes - урагана удря",
  "landslide - свлачище",
  "volcanic eruption - вулканично изригване",
  "aftershock - вторичен трус",
  "casualty - нещастен случай, пострадал",
  "molten lava - разтопена лава",
  "refugee - бежанец",
  "torrential rain - проливен дъжд",
  "tremor - трус, треперене, леко земетресение",
  "collapse - срутване, рухвам",
  "evacuate - евакуирам",
  "head towards - отправям се към",
  "put out a fire, a cigarette - гася, изгасям, потушавам",
  "spread across - разпространявам се",
  "sweep away/ across - помитам, преминавам през",
  "tsunami engulfs the city - цунамито поглъща града",
  "prone to - предразположен, склонен към",
  "given that - при, при положение че, като се приеме",
  "burst - избухвм, пръсвам се, спуквам се",
  "beneath the debris - под отломките, остатъци",
  "increase-decrease - повишавам-намалявам (се), снижавам (се)",
  "destruction - разруха, разрушение, унищожение",
  "first aid - първа помощ",
  "fumes - изпарения",
  "go missing - изчезвам",
  "gradual slope - полегат склон",
  "grateful - благодарен, признателен",
  "headquarters - щаб, седалище",
  "humanitarian - хуманитарен",
  "pie chart - кръгова диаграма",
  "powder - прах, пудра",
  "proportion - пропорция, съотношение",
  "route - маршрут, курс, път",
  "significant - значителен, знаменателен, важен, значим",
  "steadily - постоянно, неотклонно, стабилно",
  "steady - устойчив, стабилен, постоянен",
  "storm - буря, вихрушка",
  "unsinkable - непотопяем",
  "stand in awe of - стоя изпълнен с възхищение, благоговея пред",
  "belch out - изригвам, бълвам, изхвърлям със сила",
  "chilly - мразовит",
  "curiosity - любопитство",
  "disrupt/ion - прекъсвам, разтурвам, нарушавам",
  "establish - установявам, създавам, основавам",
  "extent - степен, размер, обхват",
  "fair share of - полагаема част, немалка част",
  "fissure - пукнатина, цепнатина, пролука",
  "glacier - глетчер, ледник",
  "privilege - привилегия",
  "vent - отдушник, клапа",
  "catastrophic consequences - катастрофални последствия",
  "in anticipation of - в очакване на",
  "turn out to be - оказва се, че е",
  "range in size - варират по размер",
  "recede - оттеглям се, отстъпвам",
  "infectious disease - заразна болест",
  "every detail counts - всеки детайл е от значение",
  "beforehand - предварително, предсрочно, от по-рано",
  "death sentence - смъртна присъда",
  "mortality rate - смъртност",
  "dip - потапям, топвам",
  "have a relaxing dip - почивам си, дремвам",
  "bewildered - объркан, озадачен",
  "make rational decisions - взимам разумни, смислени решения",
  "peer pressure - натиск, насилствено влияние от връстници",
  "overwhelming - поразителен, изумителен; съкрушителен",
  "overwhelming majority - преобладаващо мнозинство",
  "safety procedures/ regulations - правилник за безопастност",
  "take precautions against - вземам предпазни мерки п/в",
  "measures include monthly drills - мерките включват месечни обучения",
  "retreat - оттеглям се, отстъпвам",
  "simulation machines - симулиращи апарати, машини",
  "thankfully - за щастие, с благодарност",
  "it's highly likely/unlikely - много/ малко веротно е",
  "imminent danger - предстоящa надвиснала опастност",
  "storage facilities - складове, хранилища",
  "come up with the initial concept - първоначалната концепция",
  "wipe out - заличавам, унищожавам",
  "to break out (epidemic) - избухва епидемия",
  "blaze - ярък пламък, огнен език, буен огънпламтя, пламък",
  "consultations - консултации, съветвания",
  "wildlife habitat - местообитаване на дивите животни",
  "breath in volcanic dust - вдишвам вулканичен прах",
  "people are forced to - хората са принудени да",
  "forest fires rage - бушуват горски пожари",
  "falling debris - падащи отломки",
  "quake - треса се, треперя, клатя се, земетресение",
  "precautions are taken - взети са предпазни мерки",
  "contaminate - заразявам, замърсявам, разлагам",
  "raise funds for charity - набиране на средства за благотворителност",
  "all too soon - твърде скоро",
  "once in a lifetime experience - незабравимо преживяване",
  "urban - градски",
  "suburban - крайградски, от педградията",
  "rural area - селски район",
  "forecast - предвиждам, предсказвам, прогноза за времето",
  "waste - отпадъци",
  "litter - боклук, смет",
  "pour - изливам, наливам",
  "drizzle - ръми, ситен дъжд",
  "flood - наводнение,наводнявам",
  "reservoir - резервоар",
  "puddle - локва",
  "pond - езерце",
  "thunder - гръм, гръмотевица",
  "lightning - мълния, светкавица",
  "plain - равнина; обикновен, прост",
  "extinct - изчезнал (вид)",
  "endangered species - застрашени видове",
  "call for - повиквам, извиквам помощ, линейка/ require; need; demand",
  "call off - отменям, отказвам се от/cancel",
  "clear up - изяснявам се (за време)/ become brighter and better",
  "cut off - отрязвам, прекъсвам/ make a place impossible to reach",
  "die down - затихва, утихва, замира",
  "do up - поправям, ремонтирам/ repair, paint or improve",
  "face up to - изправям се срещу, пред/ accept sth and try to deal with it",
  "get sb down - make sb feel sad or lose hope",
  "put sth down to - отдавам го на/ suggest that sth is the result of",
  "put out - гася, потушавам",
  "stand for - означава; понасям",
  "tear down - събарям/destroy or remove a building a statue",
  "throw away - хвърлям, изхвърлям/ discard, get rid off",
  "control - take, lose, have, out of",
  "have an effect - on sb/sth",
  "an end - come to, reach",
  "fuss about sth - make, cause",
  "sight of - catch, lose",
  "at the sight of - при вида на",
  "at first sight - на, от пръв поглед",
  "household waste - битов отпадък",
  "blizzard - снежна буря, виелица",
  "frost - мраз, скреж, слана",
  "fossil fuels - изкопаеми горива",
  "acid rain - киселинен дъжд",
  "tidal energy - енергия от приливна вълна",
  "a bird in the hand is worth two in the bush - нещо, което вече имаш е по-добре от това, което може да получиш",
  "a little bird told me - някой не иска да каже откъде е получил информацията",
  "a wolf in sheep's clothing - човек или нещо, което изглежда приятелски или безобидно, но наистина е враждебно",
  "to walk at a snail's pace - много бавно",
  "to have butterflies in the stomach - чувствам се много нервен",
  "Don't count your chickens before they are hatched - не планирай събития, които могат или не могат да се случат",
  "as stubborn as a mule - изключително упорит",
  "white elephant - скъпо и безполезно притежание",
  "fox somebody - заблуждавам, измамвам в умен начин",
  "lame duck - има проблеми и се нуждае от помощ",
  "for donkeys' years - изключително дълго време",
  "take the bull by the horns - правя нещо трудно по бърз и решителен начин",
  "bucketing down - силно вали",
  "sweltering - много горещо",
  "roasting - много горещо",
  "boiling - много горещо",
  "make it heavy weather of something - правя нещо ненужно трудно и сложно",
  "every cloud has a silver lining - във всяка лоша ситуация има нещо положително",
  "steal thunder - взимам заслугата за нещо, което е направено от някого друг",
  "a storm in a teacup - много шум за нещо, което е много малко",
  "on cloud nine - изключително щастлив и възбуждан",
  "over the moon - изключително щастлив и възбуждан",
  "---"
    ];

    words.forEach(function(word) {
        if (word.toLowerCase().includes(input)) {
            let listItem = document.createElement('li');
            listItem.textContent = word;
            resultsList.appendChild(listItem);
        }
    });

    if (resultsList.children.length > 0) {
        resultsList.style.display = 'block';
    } else {
        resultsList.style.display = 'none';
    }
});

document.addEventListener('click', function(event) {
    if (!event.target.closest('.search-container')) {
        document.getElementById('results-list').style.display = 'none';
    }
});
