document.getElementById('search-input').addEventListener('input', function() {
    let input = this.value.toLowerCase();
    let resultsList = document.getElementById('results-list');
    resultsList.innerHTML = '';

    let words = [
        "gig": "концерт, представление",
  "lighting": "осветление",
  "lyrics": "текст на песен",
  "performance": "изпълнение, представяне",
  "soundtrack": "музика към филм",
  "stage": "сцена, подиум",
  "fileSharingSite": "сайт за споделяне на файлове",
  "liveStream": "предаване на живо",
  "peerToPeer": "от връстник на връстник",
  "purchase": "покупка",
  "stream": "слушане онлайн",
  "transferMusic": "прехвърлям музика",
  "blockbuster": "много успешен филм",
  "boxOffice": "каса за билети за филм/ театър",
  "drawback": "недостатък",
  "feedback": "обратна връзка",
  "outcome": "постигнат резултат",
  "pageTurner": "интересна/вълнуваща книга",
  "screenplay": "сценарий",
  "turnout": "посетители, публика",
  "brandNew": "чисто нов",
  "thoughtProvoking": "кара те да се замислиш",
  "appealing": "умоляващ, привлекателен, трогателен",
  "tiredCliche": "изтъркано, остаряло клише",
  "convincing": "убедителен",
  "credible": "правдоподобен, достоверен",
  "gripping": "увлекателен, завладяващ",
  "hilarious": "смешен, забавен",
  "intricate": "сложен, заплетен",
  "intriguing": "интригуващ, заинтригуващ",
  "loyalty": "лоялност, преданост, вярност",
  "moving": "трогателен",
  "objectTo": "възразявам срещу",
  "blurb": "кратко описание на книгата на последната страница",
  "plot": "сюжет",
  "predictable": "предсказуем",
  "release": "пускам, освобождавам",
  "spectacular": "грандиозен, поразителен, зрелищен",
  "stunning": "зашеметяващ, слисващ, поразително красив",
  "thrilling": "вълнуващ",
  "unconvincing": "неубедителен",
  "uninspiring": "немотивиращ, безвкусен",
  "vivid": "ярък, жив образ/ картина",
  "transcendBarriers": "прехвърлям, надминавам бариери",
  "masterACraft": "усъвършенствам се в занаят",
  "beFairlyCompensated": "честно, справедливо компенсиран",
  "standUpAndTakeNote": "да се изправи и да заяви",
  "highEndFashion": "висша мода",
  "devalue": "обезценявам, намалявам стойността",
  "takesRoughly": "приблизително отнема",
  "royalty": "хонорар, възнаграждение",
  "isItAnyWonderThen": "учудващо/ странно ли е тогава, че",
  "giveWayTo": "отстъпвам място (на ново, по-добро)",
  "moneyDryUp": "средствата секват, спират",
  "IForOneBelieveThat": "аз лично, вярвам, че",
  "beInHighDemand": "изключително се търси нщ",
  "theSystemIsImbalancedAndBroken": "системата е несправедлива и нарушена",
  "afterAll": "все пак, в края на краищата",
  "pledgeMoneyFor": "залагам пари",
  "getSthOffTheGround": "да си стъпи на краката, да заработи",
  "viaTheNetwork": "чрез мрежата",
  "entrepreneur": "предприемач",
  "toBackAProject": "подкрепям проект",
  "guidance": "ръководство, упътване",
  "inYearsToCome": "през следващите години",
  "indication": "признаци, посочване, означаване",
  "bringAnIdeaToLife": "осъществявам идея, вдъхвам живот на идея",
  "atOnesOrItsCore": "по своята същност, в основата си",
  "dryUp": "пресъхва, секва, свършва",
  "IForOne": "аз лично",
  "countOn": "разчитам на",
  "dropOff": "заспивам",
  "fallFor": "хващам се, да повярвам",
  "getAlongWith": "разбирам се с",
  "goDownAs": "ще остане запомнен",
  "letDown": "разочаровам",
  "nameAfter": "кръщавам на",
  "putOn": "поставям на сцена",
  "showOff": "фукам се, хваля се",
  "takeAfterSb": "метнал съм се, приличам на, напомням на",
  "takeOff": "преуспява, изстрелва на върха",
  "rehearse": "репетирам",
  "makeAnImpressionOnSb": "правя впечатление",
  "beUnderTheImpressionThat": "оставам с впечатлението, струва ми се",
  "roarWithLaughter": "смея се гръмогласно",
  "vary": "варирам, меня, променям, (видо) изменям (се)",
  "variable": "променлив, непостоянен, несигурен",
  "varying": "вариращ, променлив",
  "variably": "по различен начин",
  "various": "различни, разнообразни",
  "variation": "разновидност, различие, видоизменение, вариране",
  "aVarietyOf": "разнообразие от",
  "converse": "разговарям",
  "bore": "досаждам/омръзвам на, отегчавам",
  "sketch": "скица; скицирам",
  "interval": "антракт; пауза, интервал",
  "conductor": "диригент, кондуктор",
  "announcer": "говорител",
  "playwright": "драматург",
  "composer": "композитор",
  "novelist": "писател романист",
  "editor": "издател, редактор",
  "outOfDate": "остарял; с изтекъл срок на годност",
  "grippingPlot": "увлекателен, завладяващ сюжет",
  "currentAffairs": "текущи събития",
  "contemporaryArt": "съвременно изкуство",
  "aDullFilm": "тъп, скучен филм",
  "readable": "увлекателен, интересен, забавен",
  "toBoo": "освирквам",
  "chorus": "хор",
  "closeUpImages": "кино кадър/снимка отблизо, едър план",
  "dressRehearsal": "генерална репетиция",
  "dressCircle": "първи балкон",
  "masterpiece": "шедьовър",
  "thoroughlyEntertaining": "напълно, изключително забавно",
  "script": "сценарий, текст на актьор",
  "paperbackBook": "книга с меки корици, евтин роман",
  "hardback": "(книга с) твърда корица",
  "index": "показалец, индекс, степенен показател",
  "pickUp": "receive a radio service",
  "putOnAPerformance": "play/do/ perform a performance",
  "callOffTheConcert": "cancel, отменям концерт",
  "aBookIsComingOut": "издавам, публикувам нова книга, излиза от печат",
  "workOutAStory": "think of a story",
  "takeUpANewHobby": "start a new hobby"
    ];

    words.forEach(function(word) {
        if (word.toLowerCase().includes(input)) {
            let listItem = document.createElement('li');
            listItem.textContent = word;
            resultsList.appendChild(listItem);
        }
    });

    if (resultsList.children.length > 0) {
        resultsList.style.display = 'block';
    } else {
        resultsList.style.display = 'none';
    }
});

document.addEventListener('click', function(event) {
    if (!event.target.closest('.search-container')) {
        document.getElementById('results-list').style.display = 'none';
    }
});
